### ISSUE TITLE
publication.out is in CSV format but documentation says it's a Markdown table

### ISSUE THREAD

**Issue by gsmet** [gradle/github-actions#13]
`publication.out` is in CSV format.

But the README here https://github.com/gradle/github-actions/tree/v1-beta says that it's a Markdown table.

The documentation probably needs fixing.

(I can do it but wasn't sure how you were handling your branches)

**Comment by jprinet** [comment]
[Fixed](https://github.com/gradle/github-actions/tree/jprinet/enhance-build-scan-links-comment#maven-build-scanpublish) by dumping into a JSON format
